export const color = {
  doctor: ['#000000', '#8F9197', '#CFD4E3'],
  worker: ['#000000', '#7965EC', '#F5C987'],
  volunteer: ['#000000', '#837575', '#ED8888'],
  ordinary: ['#000000', '#758E82', '#98DEBE']
};

export const backgroundImage = {
  doctor: './static/images/img/doctor.png',
  worker: './static/images/img/worker.png',
  volunteer: './static/images/img/volunteer.png',
  ordinary: './static/images/img/ordinary.png'
};

export const doctor = [
  './static/images/doctor/1.png',
  './static/images/doctor/2.png',
  './static/images/doctor/3.png',
  './static/images/doctor/4.png',
  './static/images/doctor/5.png',
  './static/images/doctor/6.png',
  './static/images/doctor/7.png',
  './static/images/doctor/8.png',
  './static/images/doctor/9.png',
  './static/images/doctor/10.png',
  './static/images/doctor/11.png',
  './static/images/doctor/12.png'
];

export const worker = [
  './static/images/worker/1.png',
  './static/images/worker/2.png',
  './static/images/worker/3.png',
  './static/images/worker/4.png',
  './static/images/worker/5.png',
  './static/images/worker/6.png',
  './static/images/worker/7.png',
  './static/images/worker/8.png',
  './static/images/worker/9.png',
  './static/images/worker/10.png',
  './static/images/worker/11.png',
  './static/images/worker/12.png'
];

export const ordinary = [
  './static/images/ordinary/1.png',
  './static/images/ordinary/2.png',
  './static/images/ordinary/3.png',
  './static/images/ordinary/4.png',
  './static/images/ordinary/5.png',
  './static/images/ordinary/6.png',
  './static/images/ordinary/7.png',
  './static/images/ordinary/8.png',
  './static/images/ordinary/9.png',
  './static/images/ordinary/10.png',
  './static/images/ordinary/11.png',
  './static/images/ordinary/12.png'
];

export const volunteer = [
  './static/images/volunteer/1.png',
  './static/images/volunteer/2.png',
  './static/images/volunteer/3.png',
  './static/images/volunteer/4.png',
  './static/images/volunteer/5.png',
  './static/images/volunteer/6.png',
  './static/images/volunteer/7.png',
  './static/images/volunteer/8.png',
  './static/images/volunteer/9.png',
  './static/images/volunteer/10.png',
  './static/images/volunteer/11.png',
  './static/images/volunteer/12.png'
];

export const lineData = [
  0,
  46,
  80,
  892,
  315,
  356,
  378,
  576,
  894,
  1033,
  1242,
  1967,
  1766,
  1501,
  1985,
  1379,
  1921,
  1552,
  1104,
  13436,
  3910,
  1923,
  1548,
  1690,
  1600,
  1660,
  615,
  319,
  314,
  541,
  348,
  464,
  370,
  383,
  313,
  420,
  565,
  193,
  111,
  114,
  131,
  126,
  74,
  41,
  36,
  17,
  13,
  8,
  5,
  4,
  4,
  4,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0
];

export const listData = [
  '武汉封城。',
  '火神山医院开建。',
  '武汉市决定再建雷神山医院。',
  '同济大学附属东方医院国家紧急医学救援队发出请战书。',
  '武汉共收到社会捐款25.86亿元。',
  '火神山医院计划2月3日交付使用。',
  '雷神山医院总体进度完成90%。',
  '雷神山医院预计正式交付。',
  '防护服2月6日缺口超4万,N95口罩缺口超5万。',
  '李文亮医生去世。',
  '成都首场全球直播音乐会《抗击疫情 声援武汉》播出。',
  '武汉市中小学开始线上上课。',
  '19支重症医疗队飞抵武汉。',
  '中共中央政治局委员、国务院副总理孙春兰率中央赴湖北指导组来到湖北省疫情防控指挥部。',
  '军队增派的又一批1200名医护人员抵达武汉。',
  '融媒体短视频《武汉:我的战“疫”日记》将于2月22日起在CCTV-9播出。',
  '良品铺子2月24日IPO:募资近5亿 积极抗击武汉疫情。',
  '国家调拨的4台ECMO设备由邮航包机紧急从南京飞往武汉。',
  '累计治愈出院病例超过现有确诊病例。',
  '军委后勤保障部全军万余医护人员驰援武汉。',
  '武汉已有11家方舱医院休舱。',
  '武汉新增确诊病例首次降至20例以下。',
  '武汉方舱医院于3月10日全部休舱。',
  '习近平总书记在湖北省武汉市考察调研。',
  '武汉新增确诊病例首次降至个位数(8例)。',
  '截止至今日，武汉红十字会共接收来自全国各地乃至全世界的捐款162626.29万元。',
  '湖北发布最新疫情风险等级 除武汉外均为中低风险。',
  '武汉协和医院肿瘤中心正式关闭所有新冠肺炎隔离病区。',
  '新疆生产建设兵团援鄂医疗队共计176名队员圆满完成任务返回新疆。',
  '湖北省新增新冠肺炎确诊病例首次清零。',
  '湖北除武汉外所有市县疫情转为低风险。',
  '国产新冠肺炎疫苗已开始人体注射实验。',
  '武汉部分商超向个人开放。',
  '武汉城区疫情等级降为中低风险。',
  '湖北除武汉外解除离鄂通道管控。',
  '3月27日除武汉外所有通道卡点全部撤除，交通逐步有序恢复。',
  '武汉长江隧道和公铁隧道恢复通行。',
  '武汉无疫情小区达98.2%。',
  '多家商场恢复营业。',
  '李兰娟院士团队撤离武汉。',
  '武汉全城红灯 车辆停驶3分钟 追悼烈士和逝世同胞。',
  '1400多名医疗队员撤离。',
  '武汉解封。'
];